services:
  ci:
    build: ./ci
    ports:
      - "8085:8085"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/repo
    environment:
      - REPO_DIR=/repo
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  
  billing:
    build: ./billing
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=billing-db
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - billing-db
    restart: unless-stopped

  billing-db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./resources/db_schemas/multi-db/billingdb.sql:/docker-entrypoint-initdb.d/billingdb.sql
    restart: unless-stopped
  
  weight:
    build: ./weight
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=weight-db
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - weight-db
    restart: unless-stopped

  weight-db:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./resources/db_schemas/multi-db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
    restart: unless-stopped

